#!/usr/bin/env bash
# bootstrap.sh — one-paste install + configure dw on a secondary Mac.
#
# Generated by `dw share` on the main Mac. Usage:
#   bash <(curl -fsSL <bootstrap-url>) --this <name> --devices "n=v,n=v,..."

set -euo pipefail

err()  { printf 'bootstrap: %s\n' "$*" >&2; }
die()  { err "$*"; exit 1; }
info() { printf '%s\n' "$*"; }
ok()   { printf '✓ %s\n' "$*"; }

THIS_DEVICE=""
DEVICES_ARG=""
REPO_URL_DEFAULT="https://github.com/thrcrt/desk-switch.git"
REPO_URL="$REPO_URL_DEFAULT"
INSTALL_DIR_DEFAULT="$HOME/.local/share/dw"
INSTALL_DIR="$INSTALL_DIR_DEFAULT"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --this)        THIS_DEVICE="${2:-}"; shift 2 ;;
    --devices)     DEVICES_ARG="${2:-}"; shift 2 ;;
    --repo)        REPO_URL="${2:-}"; shift 2 ;;
    --install-dir) INSTALL_DIR="${2:-}"; shift 2 ;;
    -h|--help)
      cat <<EOF
bootstrap.sh — install dw on a secondary Mac.

  --this <name>           Name this Mac uses in the device map (required)
  --devices "n=v,n=v,..." Full device map (required)
  --repo <url>            Git URL to clone (default: $REPO_URL_DEFAULT)
  --install-dir <path>    Where to clone (default: $INSTALL_DIR_DEFAULT)
EOF
      exit 0 ;;
    *) die "unknown arg: $1" ;;
  esac
done

[ -n "$THIS_DEVICE" ] || die "missing --this <device-name>"
[ -n "$DEVICES_ARG" ] || die "missing --devices 'n=v,n=v,...'"

[ "$(uname -s)" = "Darwin" ]  || die "macOS only — got $(uname -s)"
[ "$(uname -m)" = "arm64" ]   || die "Apple Silicon required — got $(uname -m)"
command -v git >/dev/null     || die "git is required"
command -v brew >/dev/null    || die "Homebrew is required (https://brew.sh)"

if [ -d "$INSTALL_DIR/.git" ]; then
  info "Updating existing checkout at $INSTALL_DIR..."
  git -C "$INSTALL_DIR" fetch --quiet origin
  git -C "$INSTALL_DIR" reset --quiet --hard origin/HEAD || git -C "$INSTALL_DIR" pull --ff-only
else
  [ -e "$INSTALL_DIR" ] && die "$INSTALL_DIR exists but isn't a git repo. Move it aside or pick another --install-dir."
  info "Cloning $REPO_URL → $INSTALL_DIR..."
  git clone --quiet "$REPO_URL" "$INSTALL_DIR"
fi
ok "repo at $INSTALL_DIR"

"$INSTALL_DIR/install.sh"

CONFIG_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/dw"
CONFIG_FILE="$CONFIG_DIR/config.json"
mkdir -p "$CONFIG_DIR"

DEVICES_JSON='{}'
IFS=',' read -ra PAIRS <<< "$DEVICES_ARG"
for pair in "${PAIRS[@]}"; do
  name="${pair%=*}"
  code="${pair#*=}"
  [[ "$name" =~ ^[a-zA-Z0-9._-]+$ ]] || die "invalid device name: $name"
  [[ "$code" =~ ^[0-9]+$ ]]          || die "invalid input code: $code (for $name)"
  DEVICES_JSON=$(printf '%s' "$DEVICES_JSON" \
    | jq --arg n "$name" --argjson c "$code" '. + {($n): {input: $c}}')
done

printf '%s' "$DEVICES_JSON" | jq -e --arg n "$THIS_DEVICE" '.[$n]' >/dev/null \
  || die "--this '$THIS_DEVICE' is not in the --devices list"

jq -n \
  --argjson v 2 \
  --arg    dsel "1" \
  --arg    this "$THIS_DEVICE" \
  --argjson devs "$DEVICES_JSON" \
  '{version: $v, display: {selector: $dsel}, this_device: $this, devices: $devs}' \
  > "$CONFIG_FILE"
ok "wrote $CONFIG_FILE"

if [ -d /Applications/Raycast.app ]; then
  info ""
  info "Raycast detected — generating per-device script commands."
  dw setup raycast || true
fi

info ""
ok "Done. Try:"
info "  dw status"
info "  dw list"
info "  dw <other-device>     # flip the monitor"
